const versions = [
    { id: 'v1', year: '2008', name: 'Android 1.0 Apple Pie', img: 'v1.png', desc: 'El inicio de la era Android. Lanzado con el HTC Dream, introdujo servicios vitales como Google Maps, Gmail y el Android Market. Su sistema de notificaciones desplegable fue una innovación que obligó a la competencia a rediseñarse por completo. Aunque carecía de soporte para video y era estéticamente simple, demostró que un sistema de código abierto era el futuro de los smartphones globales.' },
    { id: 'v15', year: '2009', name: 'Cupcake (1.5)', img: 'v15.png', desc: 'Introdujo el teclado virtual en pantalla, permitiendo que los teléfonos dejaran de depender de teclados físicos deslizantes. Fue la primera versión en usar nombres de postres y trajo los icónicos widgets de escritorio para personalización. También habilitó la grabación de video y la carga directa a YouTube. Con Cupcake, la experiencia de usuario se volvió mucho más pulida, fluida y amigable para el consumidor común.' },
    { id: 'v16', year: '2009', name: 'Donut (1.6)', img: 'v16.png', desc: 'Esta versión permitió que Android funcionara en múltiples resoluciones de pantalla y trajo el cuadro de búsqueda rápida universal. Mejoró drásticamente la velocidad de la cámara y la galería de fotos, facilitando capturar momentos al instante. Fue fundamental para que Android llegara a dispositivos más económicos y variados. También introdujo el soporte para redes CDMA, permitiendo que Android se expandiera a más operadoras telefónicas en todo el mundo.' },
    { id: 'v20', year: '2009', name: 'Eclair (2.1)', img: 'v20.png', desc: 'Trajo la navegación GPS gratuita de Google Maps, lo que revolucionó la forma en que usamos los teléfonos para viajar. Añadió fondos de pantalla animados y soporte para múltiples cuentas de correo en un solo lugar. La cámara recibió flash digital y zoom por primera vez. Fue el salto que posicionó a Android como una plataforma profesional y madura. También optimizó la velocidad de escritura con un teclado virtual mucho más inteligente.' },
    { id: 'v22', year: '2010', name: 'Froyo (2.2)', img: 'v22.png', desc: 'Se enfocó en el rendimiento extremo con el compilador JIT, haciendo que el sistema fuera hasta cinco veces más rápido que antes. Introdujo el Hotspot Wi-Fi para compartir internet y el soporte para Adobe Flash en el navegador. Las notificaciones push de Google mejoraron la sincronización de datos en tiempo real de manera masiva. También permitió instalar aplicaciones en la tarjeta SD, una función muy solicitada por los usuarios para liberar espacio interno.' },
    { id: 'v23', year: '2010', name: 'Gingerbread (2.3)', img: 'v23.png', desc: 'Rediseñó la interfaz con tonos oscuros para ahorrar batería en las nuevas pantallas AMOLED. Introdujo el soporte para tecnología NFC y sensores como el giroscopio para mejorar los juegos móviles. También habilitó el soporte para cámaras frontales, dando inicio a la era de las selfies y videollamadas. Fue una versión tan eficiente y estable que muchos dispositivos la utilizaron como base durante varios años seguidos.' },
    { id: 'v40', year: '2011', name: 'Ice Cream Sandwich (4.0)', img: 'v40.png', desc: 'Unificó el diseño de tablets y celulares bajo el estilo Holo y la elegante fuente Roboto. Introdujo botones de navegación virtuales y la capacidad de cerrar apps deslizando el dedo lateralmente. Estrenó el desbloqueo facial y Android Beam para compartir archivos con solo tocar dos teléfonos. Representó la madurez estética definitiva de Android, haciendo que el sistema fuera coherente, moderno y muy atractivo visualmente para todos.' },
    { id: 'v41', year: '2012', name: 'Jelly Bean (4.1)', img: 'v41.png', desc: 'Project Butter llegó para hacer que la interfaz corriera a 60fps constantes, eliminando cualquier rastro de lentitud. Google Now debutó ofreciendo información predictiva antes de que el usuario la buscara. Las notificaciones se volvieron expandibles y mucho más interactivas que antes. Se añadió soporte para audio multi-canal y perfiles de usuario en tablets. Fue la versión que consolidó la fluidez extrema y la suavidad táctil que los usuarios esperaban.' },
    { id: 'v44', year: '2013', name: 'KitKat (4.4)', img: 'v44.png', desc: 'Optimizada para dispositivos con hardware limitado, permitiendo que Android moderno corriera con solo 512MB de RAM. Introdujo el comando OK Google y el modo inmersivo para ocultar las barras y disfrutar contenido a pantalla completa. Los contactos se organizaban inteligentemente según la frecuencia de uso. Fue una actualización estratégica para combatir la fragmentación y llevar lo último en software a dispositivos de entrada en mercados emergentes.' },
    { id: 'v50', year: '2014', name: 'Lollipop (5.0)', img: 'v50.png', desc: 'Llegó Material Design, una revolución visual basada en sombras, capas y animaciones realistas de alta calidad. El motor interno cambió a ART, mejorando el rendimiento de las aplicaciones y la autonomía de la batería. Las notificaciones ahora aparecían en la pantalla de bloqueo para un acceso rápido. Soporte para 64 bits y el Proyecto Volta para gestión de energía fueron cambios técnicos clave. Fue una renovación total que transformó la percepción estética del sistema operativo.' },
    { id: 'v60', year: '2015', name: 'Marshmallow (6.0)', img: 'v60.png', desc: 'Se enfocó en la privacidad con el nuevo sistema de permisos granulares por cada aplicación individualmente. Introdujo el Modo Doze, que ahorraba batería de forma masiva cuando el teléfono estaba en reposo total. Google Now on Tap permitía buscar contexto sobre cualquier cosa que estuviera en pantalla. También añadió soporte nativo para lectores de huellas y USB Tipo-C. Fue una versión que priorizó la seguridad, la eficiencia energética y la estabilidad técnica.' },
    { id: 'v70', year: '2016', name: 'Nougat (7.0)', img: 'v70.png', desc: 'Introdujo la multitarea real nativa con el modo de pantalla dividida para usar dos apps a la vez. Las respuestas rápidas desde notificaciones se volvieron más potentes y el menú de ajustes se hizo personalizable. Nougat trajo mejoras gráficas con Vulkan API, ideal para jugadores exigentes. También implementó actualizaciones en segundo plano para no interrumpir el uso. Fue una versión diseñada para aumentar la productividad y exprimir el hardware potente de la época.' },
    { id: 'v80', year: '2017', name: 'Oreo (8.0)', img: 'v80.png', desc: 'Introdujo el modo Picture-in-Picture para videos flotantes y los puntos de notificación sobre los iconos de aplicaciones. Logró que los dispositivos encendieran el doble de rápido y reforzó la seguridad con Google Play Protect activo. Estrenó Android Go para hardware limitado y los iconos adaptativos para estandarizar la estética visual. Fue una versión de refinamiento que hizo al sistema mucho más inteligente, rápido y seguro ante amenazas externas.' },
    { id: 'v90', year: '2018', name: 'Pie (9.0)', img: 'v90.png', desc: 'La inteligencia artificial tomó el protagonismo con batería y brillo adaptativo que aprenden del usuario. Introdujo la navegación por gestos eliminando los clásicos botones inferiores de la pantalla. Bienestar Digital debutó para ayudar a controlar el tiempo de uso del móvil y reducir distracciones. Las acciones en apps predijeron lo que el usuario quería hacer según su rutina diaria. Fue una actualización que hizo que Android se sintiera más orgánico, predictivo y humano.' },
    { id: 'v10', year: '2019', name: 'Android 10', img: 'v10.png', desc: 'La primera versión en dejar atrás los nombres de postres para adoptar una identidad global más simple. Introdujo el Modo Oscuro nativo y opciones de privacidad mucho más estrictas para la ubicación. El soporte para plegables se integró profundamente en el código del sistema. Las respuestas inteligentes sugirieron acciones directas como abrir mapas desde un chat. Fue una versión centrada en la privacidad del usuario y la adaptación a nuevos formatos de hardware.' },
    { id: 'v11', year: '2020', name: 'Android 11', img: 'v11.png', desc: 'Se centró en las conversaciones con burbujas de chat y una sección de mensajería prioritaria en las notificaciones. El control de dispositivos inteligentes se integró en el botón de encendido para un acceso instantáneo. Permisos temporales y grabación de pantalla nativa fueron añadidos para mejorar la experiencia. Las notificaciones se organizaron para separar las charlas personales de las alertas de sistema. Fue una actualización pensada para facilitar la comunicación y el control del hogar.' },
    { id: 'v12', year: '2021', name: 'Android 12', img: 'v12.png', desc: 'Llegó Material You, permitiendo que el sistema cambie de color automáticamente basado en el fondo de pantalla elegido. El panel de privacidad introdujo indicadores visuales cuando se usa la cámara o el micrófono. El rendimiento se optimizó para ser más fluido y responder mejor a los toques. Las animaciones se volvieron elásticas y llenas de vida, dando una sensación de modernidad extrema. Fue la actualización más colorida y personalizable en la historia reciente de Android.' },
    { id: 'v15r', year: '2024', name: 'Android 15', img: 'v15r.png', desc: 'Enfocado en seguridad absoluta con el Espacio Privado para ocultar apps bajo biometría. Incluye detección de robo mediante IA que bloquea el equipo si alguien lo arrebata de tus manos violentamente. La conectividad satelital nativa ahora permite emergencias en zonas sin cobertura. Optimiza la multitarea en tablets permitiendo fijar apps en la barra de tareas. Es la versión más inteligente, segura y eficiente hasta la fecha, diseñada para el hardware del futuro.' }
];

const container = document.getElementById('timeline-content');

versions.forEach(v => {
    const item = document.createElement('div');
    item.className = 'timeline-item';
    item.onclick = () => openModal(v.id);
    item.innerHTML = `
        <div class="icon-box"><img src="${v.img}" alt="${v.name}"></div>
        <div class="dot"></div>
        <div class="year">${v.year}</div>
    `;
    container.appendChild(item);
});

function openModal(id) {
    const data = versions.find(v => v.id === id);
    document.getElementById('modal-content').innerHTML = `
        <h2>${data.name}</h2>
        <p>${data.desc}</p>
    `;
    document.getElementById('overlay').style.display = 'flex';
}

function closeModal() {
    document.getElementById('overlay').style.display = 'none';
}