const versions = [
    { id: 'v1', year: '2008', name: 'Android 1.0 Apple Pie', img: 'v1.png', desc: 'El inicio de todo. Lanzado con el HTC Dream, esta versión introdujo servicios que hoy son pilares, como Google Maps, Gmail y el Android Market original. Su sistema de notificaciones desplegable fue revolucionario, permitiendo a los usuarios gestionar alertas de una forma mucho más eficiente que la competencia. Aunque carecía de una interfaz pulida y soporte para video, sentó las bases de la libertad de código abierto. Fue el primer paso para demostrar que Google podía competir seriamente en el mercado de smartphones.' },
    { id: 'v15', year: '2009', name: 'Cupcake (1.5)', img: 'v15.png', desc: 'Cupcake fue la versión que inició la famosa tradición de nombrar las actualizaciones con postres. Introdujo el teclado virtual en pantalla, lo que permitió que los fabricantes diseñaran teléfonos sin necesidad de teclados físicos. Trajo consigo el soporte para widgets de terceros, permitiendo ver información en tiempo real sin abrir aplicaciones. También habilitó por primera vez la grabación de video y la subida directa de contenido a YouTube. Fue una actualización que pulió enormemente la experiencia de usuario diaria.' },
    { id: 'v16', year: '2009', name: 'Donut (1.6)', img: 'v16.png', desc: 'Donut expandió el alcance de Android al permitir que el sistema funcionara en diversas resoluciones de pantalla y tamaños. Introdujo el cuadro de búsqueda rápida que permitía buscar tanto en la web como dentro del contenido del teléfono simultáneamente. La cámara recibió una interfaz mucho más rápida y se mejoró la integración con la galería de fotos. Fue clave para que Android llegara a una mayor variedad de dispositivos económicos y de gama alta. Además, trajo mejoras importantes en la velocidad de ejecución de aplicaciones.' },
    { id: 'v20', year: '2009', name: 'Eclair (2.0/2.1)', img: 'v20.png', desc: 'Eclair trajo la navegación GPS paso a paso de Google Maps totalmente gratuita, cambiando el mercado de los viajes para siempre. Añadió soporte para fondos de pantalla animados y la posibilidad de agregar múltiples cuentas de correo electrónico al dispositivo. La cámara recibió soporte para flash digital y zoom, convirtiendo al móvil en una herramienta multimedia mucho más capaz. Fue el salto necesario para que Android fuera visto como una plataforma profesional y no solo un experimento. Introdujo también el soporte para Bluetooth 2.1.' },
    { id: 'v22', year: '2010', name: 'Froyo (2.2)', img: 'v22.png', desc: 'Froyo se enfocó en el rendimiento bruto mediante el compilador JIT, haciendo que el sistema fuera hasta cinco veces más rápido. Introdujo la función de Hotspot Wi-Fi, permitiendo compartir los datos móviles con otros dispositivos de forma nativa. Fue la última versión en soportar Adobe Flash de manera integral en el navegador web. También añadió la posibilidad de instalar aplicaciones en la tarjeta SD para ahorrar memoria interna. Las notificaciones push de Google mejoraron la sincronización de datos en tiempo real de forma masiva.' },
    { id: 'v23', year: '2010', name: 'Gingerbread (2.3)', img: 'v23.png', desc: 'Rediseñó la interfaz con tonos oscuros para optimizar las pantallas OLED y mejorar la vida de la batería. Introdujo el soporte para tecnología NFC, permitiendo los primeros pasos hacia los pagos móviles y el intercambio de archivos. Añadió soporte nativo para múltiples cámaras y sensores de giroscopio para juegos más inmersivos. Fue una de las versiones más estables y duraderas de la historia de Android. Muchos dispositivos de gama baja la utilizaron durante años debido a su increíble eficiencia de recursos.' },
    { id: 'v30', year: '2011', name: 'Honeycomb (3.0)', img: 'v30.png', desc: 'Una versión única diseñada exclusivamente para tablets, introduciendo la interfaz holográfica denominada Tron. Eliminó la necesidad de botones físicos, reemplazándolos por los botones virtuales de navegación que conocemos actualmente. Trajo una gestión de multitarea mucho más visual y un panel de notificaciones rediseñado para pantallas grandes. Aunque no llegó a los teléfonos, sirvió como el laboratorio de diseño para lo que sería Android 4.0. Fue fundamental para entender cómo Android debía escalar a pantallas de alta resolución.' },
    { id: 'v40', year: '2011', name: 'Ice Cream Sandwich (4.0)', img: 'v40.png', desc: 'Unificó el diseño de tablets y celulares bajo el estilo Holo y la icónica fuente Roboto. Introdujo el desbloqueo facial y la capacidad de cerrar aplicaciones deslizando el dedo en la lista de tareas recientes. Android Beam debutó aquí, permitiendo compartir fotos y contactos simplemente tocando dos teléfonos mediante NFC. Representó la madurez estética de Android, haciendo que el sistema fuera visualmente coherente y muy atractivo. También añadió carpetas en la pantalla de inicio y una gestión de datos móviles más granular.' },
    { id: 'v41', year: '2012', name: 'Jelly Bean (4.1/4.3)', img: 'v41.png', desc: 'Introdujo el Project Butter, una iniciativa para hacer que la interfaz corriera a 60 cuadros por segundo de forma constante. Google Now debutó en esta versión, ofreciendo información predictiva al usuario antes de que la solicitara. Las notificaciones se volvieron expandibles e interactivas, permitiendo responder mensajes directamente desde la barra. Se añadió soporte para audio multi-canal y la capacidad de tener múltiples perfiles de usuario en tablets. Fue la versión que consolidó la fluidez y suavidad que los usuarios exigían del sistema.' },
    { id: 'v44', year: '2013', name: 'KitKat (4.4)', img: 'v44.png', desc: 'KitKat fue optimizado para correr en dispositivos con hardware limitado, requiriendo apenas 512MB de memoria RAM. Introdujo el modo inmersivo que ocultaba las barras de estado para disfrutar de contenido a pantalla completa. El comando "OK Google" permitió activar el asistente de voz desde la pantalla de inicio de forma sencilla. Los contactos se organizaban inteligentemente según la frecuencia de llamadas del usuario. Fue una actualización clave para reducir la fragmentación del sistema en mercados emergentes con dispositivos económicos.' },
    { id: 'v50', year: '2014', name: 'Lollipop (5.0)', img: 'v50.png', desc: 'Representó la llegada de Material Design, un lenguaje visual basado en sombras, capas y animaciones realistas. Cambió el motor interno de Dalvik a ART, mejorando drásticamente el rendimiento de las apps y la autonomía. Las notificaciones aparecieron en la pantalla de bloqueo y el Proyecto Volta ayudó a gestionar mejor el consumo energético. Introdujo el soporte nativo para arquitecturas de 64 bits y el modo de ahorro de batería inteligente. Fue una renovación total que transformó a Android en una plataforma moderna y visualmente vibrante.' },
    { id: 'v60', year: '2015', name: 'Marshmallow (6.0)', img: 'v60.png', desc: 'Se centró en dar al usuario control total sobre su privacidad con el nuevo sistema de permisos individuales por aplicación. Introdujo el Modo Doze, una tecnología que ponía el teléfono en sueño profundo para ahorrar batería cuando no se movía. Google Now on Tap permitía obtener información contextual sobre cualquier cosa que apareciera en pantalla. También añadió el soporte nativo para lectores de huellas dactilares y conectividad USB Tipo-C. Fue una actualización de refinamiento técnico que mejoró la estabilidad y la seguridad del sistema operativo.' },
    { id: 'v70', year: '2016', name: 'Nougat (7.0)', img: 'v70.png', desc: 'Introdujo la multitarea real nativa con el modo de pantalla dividida para usar dos aplicaciones al mismo tiempo. Las respuestas rápidas desde las notificaciones se volvieron más potentes y el menú de ajustes rápidos se hizo personalizable. Nougat trajo mejoras en los gráficos con la API Vulkan, ideal para jugadores móviles de alto rendimiento. También implementó actualizaciones de sistema en segundo plano, permitiendo que el software se instalara sin interrumpir al usuario. Fue una versión enfocada en la productividad y la potencia del hardware moderno.' },
    { id: 'v80', year: '2017', name: 'Oreo (8.0)', img: 'v80.png', desc: 'Estrenó el modo Picture-in-Picture para ver videos en una ventana flotante mientras se realizaban otras tareas. Los puntos de notificación sobre los iconos de las apps ayudaron a gestionar las alertas pendientes de forma visual. Oreo se enfocó en la velocidad de arranque, logrando encender los dispositivos el doble de rápido que versiones previas. Introdujo Android Go para teléfonos de entrada y los iconos adaptativos para estandarizar la estética. La seguridad se vio reforzada con Google Play Protect operando activamente en segundo plano.' },
    { id: 'v90', year: '2018', name: 'Pie (9.0)', img: 'v90.png', desc: 'La inteligencia artificial tomó el control con la batería y el brillo adaptativo, que aprenden de los hábitos del usuario. Introdujo el nuevo sistema de navegación por gestos en lugar de los clásicos tres botones inferiores. Bienestar Digital debutó aquí para ayudar a los usuarios a controlar el tiempo que pasan frente a la pantalla de su móvil. Las acciones en apps permitieron predecir qué quería hacer el usuario a continuación según la hora del día. Pie refinó el diseño Material Design hacia formas más curvas, coloridas y amigables.' },
    { id: 'v10', year: '2019', name: 'Android 10', img: 'v10.png', desc: 'Fue la primera versión en abandonar los nombres de postres de manera pública, centrándose en una identidad más global. Introdujo el Modo Oscuro nativo en todo el sistema y nuevas opciones de privacidad para la ubicación de las aplicaciones. El soporte para teléfonos plegables comenzó a integrarse profundamente en el código del sistema operativo. Las respuestas inteligentes permitieron sugerir acciones como abrir mapas desde una dirección recibida en un chat. También mejoró el sistema de control parental con la integración directa de Family Link.' },
    { id: 'v11', year: '2020', name: 'Android 11', img: 'v11.png', desc: 'Se enfocó en las personas y las conversaciones, introduciendo las burbujas de chat para aplicaciones de mensajería. El centro de control ahora permitía gestionar dispositivos domésticos inteligentes de forma rápida y sencilla sin abrir apps. Se añadió un grabador de pantalla nativo y permisos temporales para micrófono o cámara que expiran tras un uso. Las notificaciones se organizaron por secciones, priorizando las charlas de amigos sobre las alertas de sistema. Fue una versión pensada para simplificar la comunicación diaria del usuario moderno.' },
    { id: 'v12', year: '2021', name: 'Android 12', img: 'v12.png', desc: 'Introdujo Material You, la mayor revolución visual desde Lollipop, permitiendo que todo el sistema cambie de color según el fondo de pantalla. El panel de privacidad ahora muestra exactamente qué apps usaron la cámara o el micrófono recientemente con indicadores visuales. El rendimiento del sistema se optimizó para reducir el uso de la CPU en procesos básicos, mejorando la respuesta táctil. Las animaciones se volvieron mucho más elásticas y vivas, dando una sensación de fluidez orgánica única. Fue la versión que devolvió la emoción a la personalización de Android.' },
    { id: 'v13', year: '2022', name: 'Android 13', img: 'v13.png', desc: 'Refinó Material You permitiendo que los iconos de aplicaciones de terceros también adoptaran los colores del sistema dinámicamente. Introdujo un permiso específico para notificaciones, evitando que las apps envíen alertas sin consentimiento previo explícito. Se añadió la capacidad de asignar idiomas diferentes a cada aplicación de forma individual por primera vez. Las mejoras en el portapapeles y la seguridad de fotos permitieron compartir solo archivos seleccionados. Fue una actualización centrada en dar al usuario un control milimétrico sobre su privacidad y estética.' },
    { id: 'v14', year: '2023', name: 'Android 14', img: 'v14.png', desc: 'Mejoró drásticamente la eficiencia energética para dispositivos de gran pantalla y optimizó el uso de datos en segundo plano. Introdujo la personalización profunda de la pantalla de bloqueo con nuevos relojes y accesos directos configurables. Se añadieron mejoras de accesibilidad como la notificación por flash y el escalado de fuente inteligente hasta el 200 por ciento. La seguridad se reforzó bloqueando la instalación de aplicaciones muy antiguas que no cumplen estándares actuales. Fue una versión de consolidación técnica que priorizó la salud de la batería y la personalización.' },
    { id: 'v15', year: '2024', name: 'Android 15', img: 'v15r.png', desc: 'Enfocado en la protección total con el Espacio Privado, una zona segura bajo biometría para ocultar aplicaciones sensibles. Introduce la detección de robo mediante IA, que bloquea el teléfono automáticamente si alguien lo arrebata de la mano del usuario. La conectividad satelital nativa permite enviar mensajes de emergencia en zonas sin cobertura de red tradicional de forma estándar. Optimiza la multitarea en tablets permitiendo fijar combinaciones de apps en la barra de tareas. Es la versión más inteligente hasta la fecha, priorizando la seguridad proactiva y el rendimiento.' }
];

const content = document.getElementById('timeline-content');

// Cargar todas las versiones
versions.forEach(v => {
    const item = document.createElement('div');
    item.className = 'timeline-item';
    item.onclick = () => openModal(v.id);
    item.innerHTML = `
        <div class="icon-box"><img src="${v.img}" alt="${v.name}"></div>
        <div class="dot"></div>
        <div class="year">${v.year}</div>
    `;
    content.appendChild(item);
});

function openModal(id) {
    const data = versions.find(v => v.id === id);
    document.getElementById('modal-content').innerHTML = `
        <h2>${data.name}</h2>
        <p>${data.desc}</p>
    `;
    document.getElementById('overlay').style.display = 'flex';
}

function closeModal() {
    document.getElementById('overlay').style.display = 'none';
}